version: '3'

services:
  clinica_veterinaria:
    build: clinica_veterinaria
    mem_limit: 512m
    ports:
      - "8080:8080"
    environment:
      DB_URL: dbc:mysql://clinica_vet:3306/clinica_veterinaria?createDatabaseIfNotExist=true&serverTimezone=UTC
      DB_USER: root
      DB_PASSWORD: Hgarcia8016*
    restart: always
    depends_on:
      clinica_vet:
        condition: service_healthy
  clinica_vet:
    image: mysql:8.0.33
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_PASSWORD: 1234
      MYSQL_DATABASE: clinica_veterinaria
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin","ping","-h","localhost"]
      timeout: 10s
      retries: 10
